import { useState, type FormEvent } from "react";
import { CheckCircle2, Loader2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";

const demands=["Nova instalação","Retrofit","Ampliação","Substituição","Modernização","Ainda não sei"];
const projects=["Tenho projeto","Projeto em desenvolvimento","Não tenho projeto","Preciso de uma avaliação técnica"];
export function ContactForm(){const [loading,setLoading]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);try{let attachment_path:string|null=null;const file=form.get("attachment");if(file instanceof File&&file.size>0){if(file.size>10*1024*1024)throw new Error("O arquivo deve ter até 10 MB.");const ext=file.name.split(".").pop()?.toLowerCase();if(!ext||!["pdf","doc","docx","png","jpg","jpeg"].includes(ext))throw new Error("Envie PDF, DOC, DOCX, PNG ou JPG.");attachment_path=`${crypto.randomUUID()}/${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("contact-documents").upload(attachment_path,file);if(up.error)throw up.error;}const result=await supabase.from("contact_requests").insert({name:String(form.get("name")),company:String(form.get("company")),phone:String(form.get("phone")),email:String(form.get("email")),city:String(form.get("city")),demand_type:String(form.get("demand_type")),project_status:String(form.get("project_status")),manufacturer:String(form.get("manufacturer"))||null,message:String(form.get("message")),attachment_path});if(result.error)throw result.error;setDone(true);}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar agora.");}finally{setLoading(false)}}
if(done)return <div className="border-t-2 border-accent bg-secondary p-8"><CheckCircle2 className="size-9 text-accent"/><h2 className="mt-5 text-2xl font-semibold">Solicitação recebida.</h2><p className="mt-3 leading-7 text-muted-foreground">Nossa equipe analisará as informações e entrará em contato pelos dados informados.</p></div>;
return <form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Nome" name="name"/><Field label="Empresa" name="company"/><Field label="Telefone" name="phone" type="tel"/><Field label="E-mail" name="email" type="email"/><Field label="Cidade / UF" name="city"/><Field label="Fabricante atual (opcional)" name="manufacturer" required={false}/><Select label="Tipo de demanda" name="demand_type" options={demands}/><Select label="Situação do projeto" name="project_status" options={projects}/><div className="sm:col-span-2"><Label htmlFor="message">Conte sobre a demanda</Label><Textarea id="message" name="message" required minLength={10} maxLength={3000} rows={6} className="mt-2"/></div><div className="sm:col-span-2"><Label htmlFor="attachment">Anexo opcional</Label><label className="mt-2 flex cursor-pointer items-center gap-3 border border-dashed border-border bg-secondary p-4 text-sm text-muted-foreground"><Upload className="size-5 text-accent"/><span>PDF, DOC, DOCX, PNG ou JPG — até 10 MB</span><Input id="attachment" name="attachment" type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" className="sr-only"/></label></div>{error&&<p role="alert" className="sm:col-span-2 text-sm text-destructive">{error}</p>}<div className="sm:col-span-2"><Button disabled={loading} size="lg" className="w-full bg-accent text-accent-foreground hover:bg-accent/90">{loading&&<Loader2 className="animate-spin"/>}Enviar solicitação</Button><p className="mt-3 text-xs leading-5 text-muted-foreground">Ao enviar, você autoriza o contato da THÉRMICA sobre esta solicitação.</p></div></form>}
function Field({label,name,type="text",required=true}:{label:string;name:string;type?:string;required?:boolean}){return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} minLength={required?2:undefined} maxLength={255} className="mt-2"/></div>}
function Select({label,name,options}:{label:string;name:string;options:string[]}){return <div><Label htmlFor={name}>{label}</Label><select id={name} name={name} required className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione</option>{options.map(x=><option key={x}>{x}</option>)}</select></div>}