/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as InstalacaoVrvVrfRouteImport } from './routes/instalacao-vrv-vrf'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as QualificacaoTecnicaRouteImport } from './routes/qualificacao-tecnica'
import { Route as RetrofitVrvVrfRouteImport } from './routes/retrofit-vrv-vrf'
import { Route as SistemasVrvVrfRouteImport } from './routes/sistemas-vrv-vrf'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo.$slug'
import { Route as ObrasSlugRouteImport } from './routes/obras.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalacaoVrvVrfRoute = InstalacaoVrvVrfRouteImport.update({
  id: '/instalacao-vrv-vrf',
  path: '/instalacao-vrv-vrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificacaoTecnicaRoute = QualificacaoTecnicaRouteImport.update({
  id: '/qualificacao-tecnica',
  path: '/qualificacao-tecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrofitVrvVrfRoute = RetrofitVrvVrfRouteImport.update({
  id: '/retrofit-vrv-vrf',
  path: '/retrofit-vrv-vrf',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasVrvVrfRoute = SistemasVrvVrfRouteImport.update({
  id: '/sistemas-vrv-vrf',
  path: '/sistemas-vrv-vrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConteudoRoute,
} as any)
const ObrasSlugRoute = ObrasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/instalacao-vrv-vrf': typeof InstalacaoVrvVrfRoute
  '/obras': typeof ObrasRouteWithChildren
  '/qualificacao-tecnica': typeof QualificacaoTecnicaRoute
  '/retrofit-vrv-vrf': typeof RetrofitVrvVrfRoute
  '/sistemas-vrv-vrf': typeof SistemasVrvVrfRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/obras/$slug': typeof ObrasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/instalacao-vrv-vrf': typeof InstalacaoVrvVrfRoute
  '/obras': typeof ObrasRouteWithChildren
  '/qualificacao-tecnica': typeof QualificacaoTecnicaRoute
  '/retrofit-vrv-vrf': typeof RetrofitVrvVrfRoute
  '/sistemas-vrv-vrf': typeof SistemasVrvVrfRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/obras/$slug': typeof ObrasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/instalacao-vrv-vrf': typeof InstalacaoVrvVrfRoute
  '/obras': typeof ObrasRouteWithChildren
  '/qualificacao-tecnica': typeof QualificacaoTecnicaRoute
  '/retrofit-vrv-vrf': typeof RetrofitVrvVrfRoute
  '/sistemas-vrv-vrf': typeof SistemasVrvVrfRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/obras/$slug': typeof ObrasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conteudo'
    | '/empresa'
    | '/instalacao-vrv-vrf'
    | '/obras'
    | '/qualificacao-tecnica'
    | '/retrofit-vrv-vrf'
    | '/sistemas-vrv-vrf'
    | '/conteudo/$slug'
    | '/obras/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conteudo'
    | '/empresa'
    | '/instalacao-vrv-vrf'
    | '/obras'
    | '/qualificacao-tecnica'
    | '/retrofit-vrv-vrf'
    | '/sistemas-vrv-vrf'
    | '/conteudo/$slug'
    | '/obras/$slug'
  id:
    | '__root__'
    | '/'
    | '/conteudo'
    | '/empresa'
    | '/instalacao-vrv-vrf'
    | '/obras'
    | '/qualificacao-tecnica'
    | '/retrofit-vrv-vrf'
    | '/sistemas-vrv-vrf'
    | '/conteudo/$slug'
    | '/obras/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudoRoute: typeof ConteudoRouteWithChildren
  EmpresaRoute: typeof EmpresaRoute
  InstalacaoVrvVrfRoute: typeof InstalacaoVrvVrfRoute
  ObrasRoute: typeof ObrasRouteWithChildren
  QualificacaoTecnicaRoute: typeof QualificacaoTecnicaRoute
  RetrofitVrvVrfRoute: typeof RetrofitVrvVrfRoute
  SistemasVrvVrfRoute: typeof SistemasVrvVrfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalacao-vrv-vrf': {
      id: '/instalacao-vrv-vrf'
      path: '/instalacao-vrv-vrf'
      fullPath: '/instalacao-vrv-vrf'
      preLoaderRoute: typeof InstalacaoVrvVrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualificacao-tecnica': {
      id: '/qualificacao-tecnica'
      path: '/qualificacao-tecnica'
      fullPath: '/qualificacao-tecnica'
      preLoaderRoute: typeof QualificacaoTecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrofit-vrv-vrf': {
      id: '/retrofit-vrv-vrf'
      path: '/retrofit-vrv-vrf'
      fullPath: '/retrofit-vrv-vrf'
      preLoaderRoute: typeof RetrofitVrvVrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas-vrv-vrf': {
      id: '/sistemas-vrv-vrf'
      path: '/sistemas-vrv-vrf'
      fullPath: '/sistemas-vrv-vrf'
      preLoaderRoute: typeof SistemasVrvVrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof ConteudoRoute
    }
    '/obras/$slug': {
      id: '/obras/$slug'
      path: '/$slug'
      fullPath: '/obras/$slug'
      preLoaderRoute: typeof ObrasSlugRouteImport
      parentRoute: typeof ObrasRoute
    }
  }
}

interface ConteudoRouteChildren {
  ConteudoSlugRoute: typeof ConteudoSlugRoute
}

const ConteudoRouteChildren: ConteudoRouteChildren = {
  ConteudoSlugRoute: ConteudoSlugRoute,
}

const ConteudoRouteWithChildren = ConteudoRoute._addFileChildren(
  ConteudoRouteChildren,
)

interface ObrasRouteChildren {
  ObrasSlugRoute: typeof ObrasSlugRoute
}

const ObrasRouteChildren: ObrasRouteChildren = {
  ObrasSlugRoute: ObrasSlugRoute,
}

const ObrasRouteWithChildren = ObrasRoute._addFileChildren(ObrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudoRoute: ConteudoRouteWithChildren,
  EmpresaRoute: EmpresaRoute,
  InstalacaoVrvVrfRoute: InstalacaoVrvVrfRoute,
  ObrasRoute: ObrasRouteWithChildren,
  QualificacaoTecnicaRoute: QualificacaoTecnicaRoute,
  RetrofitVrvVrfRoute: RetrofitVrvVrfRoute,
  SistemasVrvVrfRoute: SistemasVrvVrfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
